
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[391] =
    {   0,
       32,   32,   26,   26,   32,   32,   70,   69,    2,   69,
       58,   69,   69,   28,   39,   54,   64,   62,   63,   37,
       35,   61,    4,   31,   38,   32,   59,   60,   52,   34,
       51,   53,   17,   67,   68,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   65,   55,   66,    2,   26,   37,   26,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,    1,
       50,    0,    0,    0,   47,   56,    0,   44,   29,   40,
       42,   41,    4,   43,   31,   24,   23,   45,   31,   32,

       22,   49,    0,   46,   48,   17,   17,    0,    0,   17,
       17,    0,   17,   17,   17,   17,   17,   16,   17,   17,
       17,   17,   17,   17,   10,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   57,
       26,   27,   26,   22,   17,   17,   26,   17,   17,   17,
       17,   17,   17,   17,   16,   17,   17,   17,   17,   17,
       17,   10,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   33,    0,    0,    3,
       29,   23,   22,   22,    0,    0,    0,    0,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   15,

       17,    7,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       22,   22,   26,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   15,   17,    7,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,    0,    0,    0,    0,   30,
        0,    0,   16,   17,    9,   17,   17,   17,   17,   12,
       17,   17,    6,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,    5,   17,   17,   26,
       16,   17,    9,   17,   17,   17,   17,   12,   17,   17,

        6,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,    5,   17,   17,    0,    0,   21,
        0,   20,    0,    0,    0,    0,   17,   17,   17,   17,
        8,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   11,   17,   17,   17,   17,    8,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   11,
        0,    0,   17,   17,   14,   17,   13,   17,   17,   17,
       17,   17,   14,   17,   13,   17,   17,   17,   18,    0,
       17,   17,   17,   17,   17,   17,   17,   17,   19,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       29,    1,   30,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   28,   41,   42,   43,   44,
       45,   46,   28,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[59] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    1,    1,    1,    7,    1,    8,
        1,    1,    1,    9,    1,    1,    1,   10,   11,    1,
       12,   13,   10,   13,   13,   10,   13,   10,   13,   13,
       10,   13,   10,   13,   13,   10,   13,   10,   13,   10,
       13,   10,   10,   10,   10,    1,   14,    1
    } ;

static yyconst flex_uint16_t yy_base[414] =
    {   0,
        0,    0,   56,    0,    0,    0, 1111, 1328, 1328, 1108,
     1084,    0,   26, 1328, 1082, 1093,    0, 1328, 1328, 1074,
       47, 1328,   48, 1077,   50,   55, 1328, 1328, 1065, 1061,
     1058, 1328,   57, 1328, 1328,  108,  144,   81,   79,  146,
       37,  147, 1028,   77,   33,  103,  148,   31,  164,   68,
      150,   35,  158, 1328,   59, 1328, 1328, 1068,  106,  165,
      197,  225,  201,  170,  136,  202,  169,  194, 1012,  190,
       88,  249,  241,  174,  256,  158,  199,  173,  262, 1328,
     1328, 1048, 1015,  978, 1328, 1328, 1007, 1328,    0, 1328,
     1328, 1328,  992, 1328,  976, 1328,    0, 1328,  970,   99,

      957, 1328,  156, 1328, 1328,  936,  222,  217,  953,  903,
      283,  932,  287,  236,  139,  267,  290,  881,  293,  300,
      304,  242,  271,  305,  879,  200,  286,  306,  308,  311,
      323,  318,  336,  337,  322,  339,  338,  330,  353,  883,
      882, 1328,  357,  367,  372,  337,  379,  833,  353,  369,
      249,  150,  295,  370,  830,  373,  374,  386,  344,  382,
      389,  829,  359,  375,  401,  404,  409,  408,  421,  426,
      440,  427,  444,  452,  433,  459,  814,  764,  765,  787,
        0,    0,    0,  774,  708,  484,  416,  734,  478,  486,
      488,  409,  428,  490,  496,  491,  501,  506,  175,  692,

      508,  684,  354,  511,  512,  514,  516,  518,  528,  529,
      531,  530,  532,  543,  545,  548,  549,  535,  405,  566,
      560,  567,  572,  552,  558,  565,  533,  564,  578,  573,
      583,  586,  596,  459,  672,  599,  650,  566,  593,  603,
      611,  615,  616,  619,  629,  634,  635,  639,  649,  659,
      652,  664,  598,  463,  665,  640,  625,  598,  693, 1328,
      720,  609,  670,  690,  549,  696,  584,  700,  701,  706,
      756,  625,  707,  758,  760,  759,  712,  761,  708,  764,
      762,  763,  766,  776,  784,  792,  538,  636,  795,  810,
      774,  791,  496,  794,  779,  795,  781,  798,  808,  665,

      812,  815,  818,  825,  833,  832,  846,  847,  853,  860,
      867,  861,  866,  874,  439,  689,  879,  441,  410, 1328,
      901, 1328,  436,  416,    0,    0,  489,  897,  908,  829,
      350,  905,  797,  878,  927,  931,  932,  934,  935,  949,
      947,  813,  950,  880,  929,  944,  945,  346,  957,  951,
      961,  967,  971,  983,  977,  989,  993,  990,  909,  996,
      328,  309,  264, 1019,  952,  987,  955, 1021, 1024,  600,
      239, 1003, 1013, 1023, 1019, 1027, 1037,  612, 1328,   98,
     1055, 1054, 1057,  956, 1051, 1052, 1065, 1052, 1328, 1328,
     1118, 1132, 1138, 1145, 1150, 1156, 1166, 1179, 1189, 1199,

     1205, 1218, 1225, 1231, 1241, 1251, 1261, 1271, 1277, 1286,
     1296, 1306, 1314
    } ;

static yyconst flex_int16_t yy_def[414] =
    {   0,
      390,    1,    1,    3,    1,    1,  390,  390,  390,  390,
      390,  391,  390,  390,  390,  390,  392,  390,  390,  393,
      390,  390,  390,  390,  390,  394,  390,  390,  395,  390,
      390,  390,  396,  390,  390,  390,  396,   36,   36,  396,
       36,  396,   36,   36,   36,  396,  396,   36,  396,   36,
      396,   36,  396,  390,  397,  390,  390,  398,  393,  399,
      400,  390,  400,   62,   62,  400,   62,   66,   62,   62,
       62,   66,   66,   62,   66,   62,   66,   62,   66,  390,
      390,  391,  390,  390,  390,  390,  392,  390,  401,  390,
      390,  390,  390,  390,  390,  390,  402,  390,  390,  394,

      403,  390,  395,  390,  390,  404,  396,  390,  405,   36,
      396,  397,  396,   36,   36,   36,  396,   36,  396,  396,
      396,   36,   36,  396,   36,   36,   36,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,   36,  396,  397,
      398,  390,  399,  406,  407,   66,  408,   62,   66,   66,
       62,   62,   62,   66,   62,   66,   66,   66,   62,   62,
       66,   62,   62,   62,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   62,   66,  391,  390,  390,  392,
      401,  402,  409,  403,  390,  390,  390,  410,  396,  396,
      396,   36,   36,  396,  396,  396,  396,  396,   36,   36,

      396,   36,   36,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,   36,   36,  396,
      411,  406,  412,   66,   66,   66,   62,   62,   66,   66,
       66,   66,   66,   62,   62,   66,   62,   62,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   62,   62,   66,  390,  390,  390,  390,  390,
      390,  410,  396,  396,   36,  396,   36,  396,  396,  396,
      396,   36,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,   36,   36,  396,  412,
       66,   66,   62,   66,   62,   66,   66,   66,   66,   62,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   62,   62,   66,  390,  390,  390,
      261,  390,  413,  321,  261,  261,   36,  396,  396,  396,
       36,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,   36,  396,   62,   66,   66,   66,   62,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   62,   66,
      390,  390,   36,  396,  396,  396,  396,  396,  396,   36,
       62,   66,   66,   66,   66,   66,   66,   62,  390,  390,
      396,  396,  396,   36,   66,   66,   66,   62,  390,    0,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390
    } ;

static yyconst flex_uint16_t yy_nxt[1387] =
    {   0,
        8,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   14,   33,   34,   35,
       33,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       33,   45,   46,   43,   43,   47,   48,   49,   50,   51,
       52,   53,   33,   33,   33,   54,   55,   56,   57,   58,
       83,   90,  109,   96,   92,   84,  130,   93,   97,   59,
       91,   94,   99,   98,  100,   60,  106,  127,  122,  138,
      107,  123,  107,   61,  107,  108,  107,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   61,   71,   72,   69,

       69,   73,   74,   75,   76,   77,   78,   79,   61,   61,
       61,  109,  114,  125,  117,  140,   99,  107,  100,  115,
      126,  136,  106,  118,  142,  116,  107,  106,  107,   88,
      107,  108,  164,  389,  128,  107,  108,  146,  107,  110,
      107,  110,  110,  107,  110,  107,  110,  110,  107,  110,
      107,  110,  110,  107,  110,  107,  110,  111,  110,  107,
      107,  107,  107,  106,  112,  106,  106,  106,  141,  106,
      192,  154,  108,  185,  108,  108,  108,  106,  108,  390,
      155,  227,   99,  106,  143,  146,  108,  119,  107,  120,
      113,  124,  108,  137,  129,  101,  139,  131,  121,  146,

      141,  151,  132,  133,  141,  141,  272,  146,  152,  167,
      159,  173,  134,  160,  153,  135,  145,  175,  146,  146,
      145,  145,  146,  146,  107,  108,  162,  107,  147,  108,
      108,  107,  107,  163,  186,  146,  187,  146,  161,  146,
      146,  106,  174,  156,  145,  157,  146,  150,  202,  107,
      108,  146,  146,  108,  158,  107,  148,  146,  148,  148,
      146,  148,  146,  148,  148,  146,  148,  146,  148,  148,
      146,  148,  146,  148,  149,  148,  146,  146,  146,  146,
      165,  112,  146,  191,  146,  107,  199,  166,  385,  168,
      146,  107,  146,  146,  169,  170,  226,  146,  146,  146,

      176,  146,  106,  146,  171,  146,  106,  172,  146,  106,
      193,  108,  106,  381,  146,  108,  107,  200,  108,  106,
      107,  108,  190,  106,  106,  106,  194,  106,  108,  203,
      106,  189,  108,  108,  108,  107,  108,  106,  228,  108,
      196,  106,  106,  380,  146,  204,  108,  205,  206,  197,
      108,  108,  198,  201,  208,  106,  106,  106,  106,  207,
      141,  214,  209,  379,  108,  108,  108,  108,  212,  218,
      141,  219,  106,  210,   99,  141,  143,  216,  146,  107,
      146,  108,  147,  213,  215,  217,  221,  101,  234,  146,
      211,  263,  220,  146,  146,  146,  146,  184,  141,  107,

      108,  224,  106,  107,  225,  146,  229,  237,  146,  188,
      146,  146,  146,  146,  146,  146,  146,  146,  238,  390,
      231,  146,  146,  232,  146,  146,  146,  146,  235,  146,
      146,  146,  146,  186,  233,  187,  288,  236,  146,  243,
      239,  146,  146,  240,  146,  146,  241,  146,  322,  146,
      146,  146,  146,  146,  107,  265,  146,  242,  107,  362,
      146,  146,  146,  245,  146,  244,  249,  146,  146,  146,
      146,  247,  253,  146,  254,  266,  267,  107,  146,  146,
      246,  146,  146,  146,  361,  146,  248,  146,  146,  250,
      300,  251,  146,  146,  316,  146,  146,  106,  255,  252,

      146,  186,  146,  259,  146,  106,  108,  106,  146,  106,
      106,  146,  146,  260,  108,  106,  108,  264,  108,  108,
      106,  268,  263,  263,  108,  106,  270,  106,  269,  108,
      106,  106,  363,  106,  108,  106,  108,  106,  107,  108,
      108,  271,  108,  263,  108,  146,  108,  106,  106,  106,
      106,  106,  263,  275,  273,  274,  108,  108,  108,  108,
      108,  277,  106,  141,  106,  276,  280,  106,  106,  287,
      141,  108,  279,  108,  278,  141,  108,  108,  281,  293,
      284,  282,  146,  261,  107,  106,  221,  107,  286,  292,
      183,  283,  285,  146,  108,  146,  291,  184,  107,  146,

      291,  146,  262,  291,  146,  297,  146,  289,  146,  296,
      146,  294,  295,  146,  146,  146,  146,  146,  298,  146,
      261,  146,  320,  327,  146,  146,  146,  146,  291,  146,
      146,  299,  315,  107,  146,  146,  301,  146,  146,  146,
      146,  384,  146,  291,  146,  146,  302,  146,  146,  107,
      303,  146,  146,  388,  146,  146,  146,  146,  146,  305,
      146,  146,  146,  146,  304,  306,  319,  146,  146,  308,
      146,  146,  307,  331,  107,  146,  146,  146,  146,  318,
      146,  146,  146,  309,  342,  107,  146,  146,  310,  106,
      146,  146,  146,  146,  312,  146,  313,  311,  108,  146,

      146,  146,  146,  314,  146,  146,  317,  146,  146,  106,
      186,  146,  259,  348,  146,  106,  146,  146,  108,  106,
      106,  146,  260,  321,  108,  106,  106,  106,  108,  108,
      263,  106,  322,  107,  108,  108,  108,  359,  146,  323,
      108,  107,  329,  335,  263,  261,  258,  324,  263,  328,
      324,  325,  324,  325,  324,  324,  325,  324,  325,  325,
      324,  325,  324,  325,  325,  324,  325,  324,  325,  324,
      324,  324,  324,  324,  324,  106,  326,  106,  106,  106,
      106,  106,  106,  106,  108,  106,  108,  108,  108,  108,
      108,  108,  108,  183,  108,  106,  338,  180,  257,  339,

      256,  337,  330,  106,  108,  334,  332,  333,  336,  263,
      340,  106,  108,  141,  106,  146,  106,  146,  344,  177,
      108,  261,  346,  108,  146,  108,  146,  263,  146,  341,
      343,  291,  146,  146,  146,  146,  146,  146,  146,  146,
      262,  146,  291,  146,  345,  366,  146,  146,  106,  146,
      146,  146,  370,  146,  347,  146,  146,  108,  146,  146,
      146,  146,  107,  349,  146,  350,  146,  146,  146,  291,
      146,  351,  263,  146,  146,  146,  146,  146,  146,  230,
      291,  352,  146,  390,  146,  146,  109,  146,  146,  146,
      146,  353,  354,  355,  146,  357,  146,  106,  146,  146,

      356,  146,  146,  146,  146,  146,  108,  146,  146,  291,
      146,  358,  146,  146,  360,  146,  106,  146,  146,  146,
      146,  367,  146,  371,  106,  108,  146,  106,  107,  146,
      195,  146,  324,  108,  324,  109,  108,  324,  364,  324,
      324,  365,  324,  263,  324,  324,  106,  324,  378,  324,
      106,  106,  107,  106,  106,  108,  109,  390,  146,  108,
      108,  263,  108,  108,  108,  263,  106,  263,  106,  106,
      372,  106,  146,  263,  106,  108,  183,  108,  108,  291,
      108,  146,  263,  108,  368,  146,  146,  146,  291,   95,
      369,  263,  146,  373,  146,   95,  146,  146,  146,  374,

      146,  291,  146,  146,  375,  107,  106,  291,  146,  146,
      146,   93,  146,  146,  146,  108,  291,  180,  146,  146,
      146,  179,  382,  146,  146,  291,  146,  291,  376,  146,
      146,  146,  146,  377,  146,  146,  146,  146,  106,  146,
      106,  146,  146,  106,  146,  146,  146,  108,  146,  108,
      178,  291,  108,  177,  146,  146,  146,  263,  386,  383,
      146,  146,  146,  291,  146,  146,  146,  263,  146,   80,
      146,  146,  387,  106,  106,  146,  106,  107,  146,  146,
      146,  105,  108,  108,  104,  108,  291,  291,  102,  146,
      263,  263,  146,  146,  146,  146,   95,   88,  291,  291,

      263,  146,   86,  146,  146,   85,  146,   81,  146,   80,
      390,  390,  390,  390,  390,  390,  390,  146,   82,   82,
      390,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   87,   87,  390,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   89,   89,  390,   89,
       89,  101,  101,  390,  101,  390,  101,  101,  103,  103,
      390,  390,  103,  107,  390,  107,  107,  107,  107,  112,
      390,  390,  390,  390,  390,  390,  390,  390,  112,  112,
      141,  390,  141,  390,  390,  390,  141,  390,  141,  390,
      390,  141,  144,  390,  390,  144,  144,  390,  144,  390,

      144,  144,  146,  390,  390,  390,  146,  390,  146,  146,
      146,  146,  181,  390,  181,  390,  181,  181,  182,  182,
      390,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  184,  390,  184,  390,  184,  184,  106,  390,
      106,  106,  106,  106,  188,  390,  390,  390,  390,  390,
      188,  390,  188,  188,  222,  390,  390,  390,  222,  390,
      222,  390,  222,  222,  145,  390,  390,  390,  145,  390,
      145,  145,  145,  145,  223,  390,  390,  390,  223,  390,
      223,  390,  223,  223,  183,  390,  183,  390,  183,  183,
      262,  390,  390,  262,  390,  262,  390,  262,  262,  221,

      390,  390,  390,  221,  390,  221,  390,  221,  221,  290,
      290,  390,  390,  290,  390,  290,  390,  290,  290,  323,
      390,  323,  390,  323,  390,  323,  323,    7,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390
    } ;

static yyconst flex_int16_t yy_chk[1387] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
       13,   21,   55,   25,   23,   13,   48,   23,   25,    3,
       21,   23,   26,   25,   26,    3,   33,   45,   41,   52,
       48,   41,   45,    3,   52,   33,   41,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,   36,   38,   44,   39,   55,  100,   50,  100,   38,
       44,   50,   46,   39,   59,   38,   44,   36,   39,   59,
       38,   46,   71,  380,   46,   36,   36,   71,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   37,   36,   40,   42,   47,   60,   51,
      115,   65,   37,  103,   40,   42,   47,   53,   51,  103,
       65,  152,   60,   49,   60,   65,   53,   40,  115,   40,
       37,   42,   49,   51,   47,   60,   53,   49,   40,  152,

       61,   64,   49,   49,   63,   66,  199,   76,   64,   74,
       67,   76,   49,   67,   64,   49,   61,   78,   67,   64,
       63,   66,   78,   74,  199,   61,   70,   61,   62,   63,
       66,   63,   66,   70,  108,   68,  108,   68,   68,   70,
       77,  107,   77,   66,   62,   66,   68,   63,  126,  126,
      107,   77,   62,   62,   66,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       72,   62,   73,  114,   73,  114,  122,   73,  371,   75,
       72,  122,   72,   73,   75,   75,  151,   75,  151,   75,

       79,   72,  111,   79,   75,   79,  113,   75,   75,  117,
      116,  111,  119,  363,   79,  113,  116,  123,  117,  120,
      123,  119,  113,  121,  124,  128,  117,  129,  120,  127,
      130,  111,  121,  124,  128,  127,  129,  132,  153,  130,
      119,  135,  131,  362,  153,  128,  132,  129,  130,  120,
      135,  131,  121,  124,  131,  133,  134,  137,  136,  130,
      143,  135,  132,  361,  133,  134,  137,  136,  134,  138,
      144,  138,  139,  133,  143,  145,  143,  137,  146,  138,
      146,  139,  147,  134,  136,  137,  144,  143,  159,  146,
      133,  203,  139,  159,  149,  348,  149,  144,  147,  331,

      145,  149,  145,  203,  150,  149,  154,  163,  163,  147,
      150,  154,  150,  154,  156,  157,  156,  157,  164,  324,
      156,  150,  154,  157,  164,  156,  157,  158,  160,  158,
      161,  160,  161,  187,  158,  187,  219,  161,  158,  168,
      165,  161,  165,  166,  165,  166,  167,  166,  323,  168,
      167,  168,  167,  165,  219,  192,  166,  167,  192,  319,
      168,  167,  169,  170,  169,  169,  172,  170,  172,  170,
      172,  171,  175,  169,  175,  193,  193,  193,  170,  172,
      170,  171,  175,  171,  318,  173,  171,  173,  315,  173,
      234,  174,  171,  174,  254,  174,  173,  189,  176,  174,

      176,  186,  176,  186,  174,  190,  189,  191,  234,  194,
      196,  176,  254,  186,  190,  195,  191,  190,  194,  196,
      197,  194,  189,  191,  195,  198,  196,  201,  195,  197,
      204,  205,  327,  206,  198,  207,  201,  208,  327,  204,
      205,  198,  206,  197,  207,  293,  208,  209,  210,  212,
      211,  213,  201,  206,  204,  205,  209,  210,  212,  211,
      213,  208,  214,  221,  215,  207,  211,  216,  217,  218,
      222,  214,  210,  215,  209,  223,  216,  217,  212,  227,
      215,  213,  227,  223,  218,  220,  222,  287,  217,  225,
      221,  214,  216,  224,  220,  224,  224,  222,  265,  225,

      226,  225,  223,  238,  224,  230,  226,  220,  226,  229,
      225,  228,  228,  228,  230,  238,  230,  226,  231,  229,
      262,  229,  258,  267,  231,  230,  231,  232,  232,  232,
      229,  233,  253,  267,  239,  231,  239,  233,  232,  233,
      236,  370,  236,  236,  240,  239,  240,  253,  233,  370,
      241,  236,  241,  378,  241,  240,  242,  243,  242,  243,
      244,  378,  244,  241,  242,  244,  257,  242,  243,  246,
      245,  244,  245,  272,  272,  246,  247,  246,  247,  256,
      248,  245,  248,  247,  288,  288,  246,  247,  248,  263,
      249,  248,  249,  251,  250,  251,  251,  249,  263,  237,

      250,  249,  250,  252,  251,  252,  255,  252,  255,  264,
      259,  250,  259,  300,  300,  266,  252,  255,  264,  268,
      269,  235,  259,  261,  266,  270,  273,  279,  268,  269,
      264,  277,  261,  202,  270,  273,  279,  316,  316,  261,
      277,  200,  269,  279,  266,  188,  185,  261,  277,  268,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  271,  261,  274,  276,  275,
      278,  281,  282,  280,  271,  283,  274,  276,  275,  278,
      281,  282,  280,  184,  283,  284,  282,  180,  179,  283,

      178,  281,  271,  285,  284,  276,  274,  275,  280,  278,
      284,  286,  285,  290,  289,  291,  333,  291,  295,  177,
      286,  290,  297,  289,  297,  333,  291,  285,  295,  286,
      289,  292,  292,  297,  292,  294,  296,  294,  296,  298,
      290,  298,  294,  292,  296,  333,  294,  296,  330,  299,
      298,  299,  342,  301,  299,  301,  302,  330,  302,  303,
      299,  303,  342,  302,  301,  303,  304,  302,  304,  305,
      303,  304,  330,  306,  305,  306,  305,  304,  162,  155,
      306,  307,  148,  141,  306,  305,  140,  307,  308,  307,
      308,  308,  309,  310,  309,  312,  309,  334,  307,  308,

      311,  310,  312,  310,  312,  309,  334,  313,  311,  313,
      311,  314,  310,  312,  317,  314,  328,  314,  313,  311,
      317,  334,  317,  344,  332,  328,  314,  329,  125,  344,
      118,  317,  321,  332,  321,  112,  329,  321,  328,  321,
      321,  332,  321,  329,  321,  321,  335,  321,  359,  321,
      336,  337,  110,  338,  339,  335,  109,  321,  359,  336,
      337,  335,  338,  339,  106,  337,  341,  336,  340,  343,
      345,  365,  345,  339,  367,  341,  101,  340,  343,  346,
      365,  345,  338,  367,  340,  346,  347,  346,  347,   99,
      341,  384,  350,  349,  350,   95,  346,  347,  349,  350,

      349,  352,  351,  350,  351,  384,  366,  353,  352,  349,
      352,   93,  353,  351,  353,  366,  354,   87,  355,  352,
      355,   84,  366,  353,  354,  355,  354,  356,  357,  355,
      356,  358,  356,  358,  357,  354,  357,  360,  364,  360,
      368,  356,  358,  369,  372,  357,  372,  364,  360,  368,
       83,  372,  369,   82,  373,  372,  373,  368,  374,  369,
      375,   69,  375,  376,  374,  373,  374,  364,  376,   58,
      376,  375,  377,  382,  381,  374,  383,   43,  377,  376,
      377,   31,  382,  381,   30,  383,  385,  388,   29,  377,
      381,  383,  385,  386,  385,  386,   24,   20,  386,  387,

      382,  388,   16,  385,  386,   15,  387,   11,  387,   10,
        7,    0,    0,    0,    0,    0,    0,  387,  391,  391,
        0,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  392,  392,    0,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  393,  393,    0,  393,
      393,  394,  394,    0,  394,    0,  394,  394,  395,  395,
        0,    0,  395,  396,    0,  396,  396,  396,  396,  397,
        0,    0,    0,    0,    0,    0,    0,    0,  397,  397,
      398,    0,  398,    0,    0,    0,  398,    0,  398,    0,
        0,  398,  399,    0,    0,  399,  399,    0,  399,    0,

      399,  399,  400,    0,    0,    0,  400,    0,  400,  400,
      400,  400,  401,    0,  401,    0,  401,  401,  402,  402,
        0,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  403,    0,  403,    0,  403,  403,  404,    0,
      404,  404,  404,  404,  405,    0,    0,    0,    0,    0,
      405,    0,  405,  405,  406,    0,    0,    0,  406,    0,
      406,    0,  406,  406,  407,    0,    0,    0,  407,    0,
      407,  407,  407,  407,  408,    0,    0,    0,  408,    0,
      408,    0,  408,  408,  409,    0,  409,    0,  409,  409,
      410,    0,    0,  410,    0,  410,    0,  410,  410,  411,

        0,    0,    0,  411,    0,  411,    0,  411,  411,  412,
      412,    0,    0,  412,    0,  412,    0,  412,  412,  413,
        0,  413,    0,  413,    0,  413,  413,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "project1.l"
#line 2 "project1.l"
#include<stdio.h>
#include <math.h>
#include <ctype.h>
#include <stdio.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include "y.tab.h"
int keywordcount = 0;
int linecount = 1;
int mcomment = 0;
#define SIZE 100

extern void yyerror(const char *);



#line 922 "lex.yy.c"

#define INITIAL 0
#define comment 1
#define function 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 42 "project1.l"


#line 1145 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 391 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1328 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "project1.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 45 "project1.l"
{  linecount++;  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "project1.l"
{yylval.str=strdup(yytext);int i,j,count=0; return CHARLIT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "project1.l"
{yylval.str=strdup(yytext);return NEGDIGIT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "project1.l"
{if(mcomment==0){yylval.ival = VOID;keywordcount++; return VOID;}}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "project1.l"
{if(mcomment==0){keywordcount++; return MAIN;}}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 "project1.l"
{if(mcomment==0){yylval.ival = INT;keywordcount++;  return INT;}}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "project1.l"
{ if(mcomment==0){yylval.ival = FLOAT;keywordcount++;  return FLOAT;}}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "project1.l"
{ if(mcomment==0){yylval.ival = CHAR;keywordcount++; return CHAR;}}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "project1.l"
{ if(mcomment==0){keywordcount++; return IF;}}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "project1.l"
{ if(mcomment==0){keywordcount++; return WHILE;}}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "project1.l"
{ if(mcomment==0){keywordcount++; return ELSE;}}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "project1.l"
{ if(mcomment==0){keywordcount++; return RETURN;}}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 69 "project1.l"
{ if(mcomment==0){keywordcount++; return PRINTF;}}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "project1.l"
{ if(mcomment==0){keywordcount++; return FOR;}}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 73 "project1.l"
{ if(mcomment==0){keywordcount++; }}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 75 "project1.l"
{yylval.str=strdup(yytext);return VARCHAR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 77 "project1.l"
{ }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 79 "project1.l"
{ return PREPROCESSOR;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 81 "project1.l"
{BEGIN 0;  }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "project1.l"
{ return HEADER;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 85 "project1.l"
{if(mcomment==0)printf("\nERROR 1 : Line number %d : Invalid Identifier  :%s",linecount,yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 87 "project1.l"
{   }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 89 "project1.l"
{BEGIN comment; if(mcomment==0){ mcomment = 1;}else{printf("\nERROR 2 : Line number %d : Comment Error  ",linecount);}}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 90 "project1.l"
{BEGIN comment;  linecount++;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 91 "project1.l"
;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 92 "project1.l"
{BEGIN 0;  mcomment = 0;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 95 "project1.l"
{if(mcomment==0){printf("\nERROR : Line number %d : Illegel Token  :%s",linecount,yytext);}}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 98 "project1.l"
{yylval.str=strdup(yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 100 "project1.l"
{yylval.str=strdup(yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 102 "project1.l"
{if(mcomment==0){yylval.str=strdup(yytext);
         return FDIGIT;}}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 105 "project1.l"
{ if(mcomment==0){yylval.str=strdup(yytext);
         return DIGIT;}}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 108 "project1.l"
{yylval.str=strdup(yytext); return STRING;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 110 "project1.l"
{ return ASSIGNMENT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 112 "project1.l"
{return PLUS;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 114 "project1.l"
{ return MINUS;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 116 "project1.l"
{return MULTIPLY;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 118 "project1.l"
{ return DIVIDE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "project1.l"
{printf("\nline number : %d : modulo operator %s\n",linecount,yytext);if(mcomment==0)Insert("Modulo",yytext,Search(yytext));}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 122 "project1.l"
{printf("\nline number : %d : increment operator %s\n",linecount,yytext);if(mcomment==0)Insert("Increment",yytext,Search(yytext)); return INCREMENT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 124 "project1.l"
{printf("\nline number : %d : decrement operator %s\n",linecount,yytext);if(mcomment==0)Insert("Decrement",yytext,Search(yytext)); return DECREMENT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 126 "project1.l"
{printf("\nline number : %d : add & assign operator %s\n",linecount,yytext);if(mcomment==0)Insert("Add_Assign",yytext,Search(yytext)); return S_ADD;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 128 "project1.l"
{printf("\nline number : %d : subtract & assign operator %s\n",linecount,yytext);if(mcomment==0)Insert("Sub_Assign",yytext,Search(yytext)); return S_SUB;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 130 "project1.l"
{printf("\nline number : %d : multiply & assign operator %s\n",linecount,yytext);if(mcomment==0)Insert("Mult_Assign",yytext,Search(yytext)); return S_MUL;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 132 "project1.l"
{printf("\nline number : %d : divide & assign operator %s\n",linecount,yytext);if(mcomment==0)Insert("Div_Assign",yytext,Search(yytext)); return S_DIV;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 134 "project1.l"
{printf("\nline number : %d : equal to operator %s\n",linecount,yytext);if(mcomment==0)Insert("Equal",yytext,Search(yytext)); return EQUAL;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 136 "project1.l"
{printf("\nline number : %d : modulo & assign to operator %s\n",linecount,yytext);if(mcomment==0)Insert("Mod_Assign",yytext,Search(yytext));}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 138 "project1.l"
{printf("\nline number : %d : greater than or equal to operator %s\n",linecount,yytext);if(mcomment==0)Insert("Greater_Eq",yytext,Search(yytext)); return MORE_EQUAL;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 140 "project1.l"
{printf("\nline number : %d : less than or equal to operator %s\n",linecount,yytext);if(mcomment==0)Insert("Less_Eq",yytext,Search(yytext)); return LESS_EQUAL;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 142 "project1.l"
{printf("\nline number : %d : not equal to operator %s\n",linecount,yytext);if(mcomment==0)Insert("Not_Eq",yytext,Search(yytext)); return NOT_EQUAL;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 144 "project1.l"
{printf("\nline number : %d : greater than operator %s\n",linecount,yytext);if(mcomment==0)Insert("Great",yytext,Search(yytext)); return MORE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 146 "project1.l"
{printf("\nline number : %d : less than operator %s\n",linecount,yytext);if(mcomment==0)Insert("Less",yytext,Search(yytext)); return LESS;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 148 "project1.l"
{printf("\nline number : %d : conditional operator %s\n",linecount,yytext);if(mcomment==0)Insert("Condition",yytext,Search(yytext));}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 150 "project1.l"
{printf("\nline number : %d : bit wise AND operator %s\n",linecount,yytext);if(mcomment==0)Insert("Reference/Bit_And",yytext,Search(yytext));}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 152 "project1.l"
{printf("\nline number : %d : bit wise OR operator %s\n",linecount,yytext);if(mcomment==0)Insert("Bit_Or",yytext,Search(yytext));}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 154 "project1.l"
{printf("\nline number : %d : AND operator %s\n",linecount,yytext);if(mcomment==0)Insert("Logic_And",yytext,Search(yytext));}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 156 "project1.l"
{printf("\nline number : %d : OR operator %s\n",linecount,yytext);if(mcomment==0)Insert("Logic_Or",yytext,Search(yytext));}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 158 "project1.l"
{printf("\nline number : %d : NOT operator %s\n",linecount,yytext);if(mcomment==0)Insert("Negate",yytext,Search(yytext));}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 160 "project1.l"
{printf("\nline number : %d : Colon %s\n",linecount,yytext);if(mcomment==0)Insert("Colon",yytext,Search(yytext));}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 162 "project1.l"
{printf("\nline number : %d : semi colon %s\n",linecount,yytext);if(mcomment==0)Insert("SemiColon",yytext,Search(yytext)); return SEMICOLON;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 164 "project1.l"
{printf("\nline number : %d : comma %s\n",linecount,yytext);if(mcomment==0)Insert("Coma",yytext,Search(yytext)); return COMMA;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 166 "project1.l"
{printf("\nline number : %d : open curly brace %s\n",linecount,yytext);if(mcomment==0)Insert("Open_Brace",yytext,Search(yytext)); return OCBRACE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 168 "project1.l"
{printf("\nline number : %d : closing curly brace %s\n",linecount,yytext);if(mcomment==0)Insert("Close_Brase",yytext,Search(yytext)); return CCBRACE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 170 "project1.l"
{printf("\nline number : %d : single Quot %s\n",linecount,yytext);if(mcomment==0)Insert("Single_quot",yytext,Search(yytext)); return QUOT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 172 "project1.l"
{ open1();printf("\nline number : %d : open round brace %s\n",linecount,yytext);if(mcomment==0)Insert("Open_Paran",yytext,Search(yytext)); return OPENBC;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 174 "project1.l"
{close1();printf("\nline number : %d : close round brace %s\n",linecount,yytext);if(mcomment==0)Insert("Close_Paran",yytext,Search(yytext)); return CLOSEBC;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 176 "project1.l"
{printf("\nline number : %d : open square brace %s\n",linecount,yytext);if(mcomment==0)Insert("Open_Paran",yytext,Search(yytext)); return OSBRACE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 178 "project1.l"
{printf("\nline number : %d : close square brace %s\n",linecount,yytext);if(mcomment==0)Insert("Close_Paran",yytext,Search(yytext)); return CSBRACE;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 180 "project1.l"
ECHO;
	YY_BREAK
#line 1551 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(function):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 391 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 391 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 390);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 180 "project1.l"



